theme: jekyll-theme-minimal
#theme: jekyll-theme-time-machine
#theme: jekyll-theme-slate
#theme: jekyll-theme-dinky
#logo: rfe_logo.png
logo: avatar.jpg
title: Raccoon Flash Explorer homepage
description: rfe test homepage
